import { initializeApp, getApps, getApp } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js";
import { getDatabase, ref, onValue, set, update, get } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-database.js";

const K={P:"comprasInteligenteProdutos",T:"comprasInteligenteTotal",C:"comprasInteligenteChecks",CP:"comprasInteligenteCategoria",CM:"comprasInteligenteMercadoCategoria",O:"comprasInteligenteOcultarComprados",D:"comprasInteligenteDeviceName",L:"comprasInteligenteFamilyLog",LC:"comprasInteligenteListCode"};
let produtos=[],totalCompra=0,checks={},catProd="Todas",catMerc="Todas",ocultar=true,firebaseAtivo=false,listaRef=null,ignorar=false,deferredPrompt=null,deviceName="",listCode="";
const n=v=>Number(v||0).toLocaleString("pt-BR",{minimumFractionDigits:0,maximumFractionDigits:2});
const m=v=>Number(v||0).toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2});
const e=t=>String(t??"").replaceAll("&","&amp;").replaceAll('"',"&quot;").replaceAll("<","&lt;").replaceAll(">","&gt;");
const load=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const status=t=>{document.getElementById("syncStatus").textContent=t;document.getElementById("familyStatus").textContent=t;};
const now=()=>{const d=new Date();return d.toLocaleDateString("pt-BR")+" "+d.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"});}
const getDev=()=>deviceName||(deviceName=localStorage.getItem(K.D)||"Aparelho");
const setDev=v=>{deviceName=v||"Aparelho";localStorage.setItem(K.D,deviceName);};
const getCode=()=>listCode||(listCode=localStorage.getItem(K.LC)||"");
const setCode=v=>{listCode=(v||"").trim().toLowerCase();localStorage.setItem(K.LC,listCode);};
function codeUI(){const c=getCode()||"-";document.getElementById("activeListCode").textContent=c;document.getElementById("familyCode").textContent=c;}
function log(msg){const logs=load(K.L,[]);logs.unshift({texto:msg,quando:now()});save(K.L,logs.slice(0,12));renderLogs();}
function renderLogs(){const el=document.getElementById("familyLog");const logs=load(K.L,[]);el.innerHTML=logs.length?logs.map(i=>`<div class="family-log-item"><strong>${e(i.quando)}</strong><br>${e(i.texto)}</div>`).join(""):`<div class="family-log-item">Ainda não há ações registradas.</div>`;}
function baseSnap(){return{produtos:[...produtosPadrao].map(p=>({...p,estoqueAtual:0})),totalCompra:0,checksComprados:{},atualizadoEm:Date.now()};}
async function startFirebase(){const cfg=window.firebaseSettings||{}, code=getCode(); if(!code){status("Sem código");return;} if(!cfg.enabled||!cfg.apiKey||!cfg.databaseURL||!cfg.projectId||!cfg.appId){status("Modo local");return;}
 const app=getApps().length?getApp():initializeApp({apiKey:cfg.apiKey,authDomain:cfg.authDomain,databaseURL:cfg.databaseURL,projectId:cfg.projectId,appId:cfg.appId});
 const db=getDatabase(app); listaRef=ref(db,`listas/${code}`); firebaseAtivo=true; status("Sincronização ativa");
 const ex=await get(listaRef); if(!ex.exists()) await set(listaRef,baseSnap());
 onValue(listaRef,s=>{const d=s.val()||baseSnap(); ignorar=true; produtos=Array.isArray(d.produtos)?d.produtos:baseSnap().produtos; totalCompra=Number(d.totalCompra||0); checks=d.checksComprados||{}; store(); renderAll(); ignorar=false;});
}
async function sync(){if(!firebaseAtivo||!listaRef||ignorar)return; await update(listaRef,{produtos,totalCompra,checksComprados:checks,atualizadoEm:Date.now()});}
function loadState(){produtos=load(K.P,[...produtosPadrao].map(p=>({...p,estoqueAtual:0}))); totalCompra=Number(localStorage.getItem(K.T)||"0")||0; checks=load(K.C,{}); catProd=localStorage.getItem(K.CP)||"Todas"; catMerc=localStorage.getItem(K.CM)||"Todas"; ocultar=localStorage.getItem(K.O)!=="false"; deviceName=localStorage.getItem(K.D)||"Aparelho"; listCode=localStorage.getItem(K.LC)||"";}
function store(){save(K.P,produtos); localStorage.setItem(K.T,String(totalCompra)); save(K.C,checks); localStorage.setItem(K.CP,catProd); localStorage.setItem(K.CM,catMerc); localStorage.setItem(K.O,String(ocultar)); localStorage.setItem(K.D,getDev()); localStorage.setItem(K.LC,getCode());}
function normalize(){produtos=produtos.map((p,i)=>({id:p.id||`base_${i+1}`,nome:p.nome||`Produto ${i+1}`,minimo:Math.max(0,Number(p.minimo||0)),unidade:p.unidade||"un",categoria:p.categoria||"Outros",estoqueAtual:Math.max(0,Number(p.estoqueAtual||0))}));}
function categorias(){return["Todas",...Array.from(new Set(produtos.map(p=>p.categoria||"Outros"))).sort((a,b)=>a.localeCompare(b,"pt-BR"))]}
function renderChips(id,active,cb){const el=document.getElementById(id);el.innerHTML="";categorias().forEach(cat=>{const b=document.createElement("button");b.className="chip"+(cat===active?" active":"");b.textContent=cat;b.onclick=()=>cb(cat);el.appendChild(b);});}
const visible=(p,term,cat)=>((!term||String(p.nome||"").toLowerCase().includes(term))&&(cat==="Todas"||(p.categoria||"Outros")===cat));
function updateProduct(id,field,val){const p=produtos.find(x=>x.id===id); if(!p)return; if(["nome","unidade","categoria"].includes(field))p[field]=val; else p[field]=Math.max(0,Number(String(val).replace(",", "."))||0); store(); sync(); if(field==="categoria"){renderCategories(); renderMarket();} dashboard();}
function addProduct(){const nome=document.getElementById("novoNome").value.trim(), minimo=Math.max(0,parseFloat(String(document.getElementById("novoMinimo").value).replace(",", "."))||0), unidade=document.getElementById("novoUnidade").value.trim()||"un", categoria=document.getElementById("novaCategoria").value||"Outros"; if(!nome){alert("Digite o nome do produto.");return;} produtos.unshift({id:`prod_${Date.now()}_${Math.floor(Math.random()*1000)}`,nome,minimo,unidade,categoria,estoqueAtual:0}); store(); renderAll(); sync(); document.getElementById("novoNome").value="";document.getElementById("novoMinimo").value="";document.getElementById("novoUnidade").value="un";}
function removeProduct(id){const p=produtos.find(x=>x.id===id); if(!p)return; if(!confirm(`Excluir o produto "${p.nome}"?`))return; produtos=produtos.filter(x=>x.id!==id); delete checks[id]; store(); renderAll(); sync();}
function renderProducts(filter=""){const c=document.getElementById("listaProdutos"), term=filter.trim().toLowerCase(); c.innerHTML=""; let count=0; produtos.forEach(p=>{if(!visible(p,term,catProd))return; count++; const card=document.createElement("div"); card.className="product-card"; card.innerHTML=`<div class="product-grid"><div><label class="product-label">Produto</label><input type="text" value="${e(p.nome)}" oninput="window.app.updateProduct('${p.id}','nome',this.value)" /></div><div><label class="product-label">Mínimo</label><input type="number" min="0" step="0.01" value="${p.minimo}" oninput="window.app.updateProduct('${p.id}','minimo',this.value)" /></div><div><label class="product-label">Unidade</label><input type="text" value="${e(p.unidade)}" oninput="window.app.updateProduct('${p.id}','unidade',this.value)" /></div><div><label class="product-label">Categoria</label><select onchange="window.app.updateProduct('${p.id}','categoria',this.value)">${categorias().filter(x=>x!=="Todas").map(x=>`<option value="${e(x)}" ${x===p.categoria?"selected":""}>${e(x)}</option>`).join("")}</select></div><div><label class="product-label">Em casa</label><input type="number" min="0" step="0.01" value="${p.estoqueAtual}" oninput="window.app.updateProduct('${p.id}','estoqueAtual',this.value)" /></div></div><div class="product-actions"><button class="btn btn-delete btn-full" onclick="window.app.removeProduct('${p.id}')">Excluir</button></div>`; c.appendChild(card);}); document.getElementById("contadorProdutos").textContent=`${count} produtos`;}
function listBase(){return produtos.map(p=>{const minimo=Math.max(0,Number(p.minimo||0)), estoqueAtual=Math.max(0,Number(p.estoqueAtual||0)), falta=Math.max(0,minimo-estoqueAtual); return {...p,minimo,estoqueAtual,falta,comprado:!!checks[p.id]};}).filter(i=>i.falta>0);}
function renderMarket(){const area=document.getElementById("listaCompras"), resumo=document.getElementById("listaResumo"), term=(document.getElementById("buscaMercado").value||"").trim().toLowerCase(); let itens=listBase().filter(i=>visible(i,term,catMerc)); if(ocultar)itens=itens.filter(i=>!i.comprado); const grouped={}; itens.forEach(i=>{const cat=i.categoria||"Outros";(grouped[cat]??=[]).push(i)}); area.innerHTML=""; Object.keys(grouped).sort((a,b)=>a.localeCompare(b,"pt-BR")).forEach(cat=>{const t=document.createElement("div");t.className="market-category-title";t.textContent=cat;area.appendChild(t);grouped[cat].forEach(i=>{const card=document.createElement("div");card.className="shopping-item"+(i.comprado?" comprado":"");card.innerHTML=`<div><div class="item-title">${e(i.nome)}</div><span class="qty-badge">Comprar ${n(i.falta)} ${e(i.unidade)}</span><span class="item-meta">Mínimo: ${n(i.minimo)} | Em casa: ${n(i.estoqueAtual)}</span></div><div class="market-item-actions"><button class="btn ${i.comprado?"btn-light":"btn-primary"} pick-btn" onclick="window.app.toggleBought('${i.id}')">${i.comprado?"Desmarcar":"Marcar pego"}</button></div>`;area.appendChild(card);});}); if(!itens.length)area.innerHTML=`<div class="family-log-item">Nada pendente nesta visão.</div>`; const total=listBase().length, done=listBase().filter(i=>i.comprado).length, perc=total===0?0:Math.round((done/total)*100); const bar=document.getElementById("barra"); bar.style.width=perc+"%"; bar.textContent=perc+"%"; resumo.textContent=total===0?"Tudo certo. Sua lista zerou bonito.":`${total} item(ns) faltando. ${done} já marcados.`; dashboard();}
function setBought(id,val){checks[id]=val; store(); const item=produtos.find(p=>p.id===id); if(item)log(`${getDev()} ${val?"marcou":"desmarcou"} ${item.nome}.`); renderMarket(); sync();}
function dashboard(){const itens=listBase(), done=itens.filter(i=>i.comprado).length, perc=itens.length===0?0:Math.round((done/itens.length)*100); document.getElementById("statProdutos").textContent=produtos.length; document.getElementById("statFaltando").textContent=itens.length; document.getElementById("statProgresso").textContent=perc+"%"; document.getElementById("statTotal").textContent=m(totalCompra);}
function addValue(){const field=document.getElementById("valorItem"), v=parseFloat(String(field.value).replace(",", "."))||0; totalCompra+=v; store(); document.getElementById("total").textContent=m(totalCompra); dashboard(); field.value=""; sync();}
function resetValue(){totalCompra=0; store(); document.getElementById("total").textContent=m(totalCompra); dashboard(); sync();}
function exportList(){const itens=listBase(); if(!itens.length){alert("A lista de compras está vazia."); return;} const lines=["COMPRAS INTELIGENTE","",`Código: ${getCode()}`,""]; itens.forEach(i=>lines.push(`- ${i.nome} | Comprar: ${n(i.falta)} ${i.unidade} | Categoria: ${i.categoria} | ${i.comprado?"PEGUEI":"PENDENTE"}`)); lines.push("",`Total de itens: ${itens.length}`,`Total acumulado: R$ ${m(totalCompra)}`); const blob=new Blob([lines.join("\\n")],{type:"text/plain;charset=utf-8"}), url=URL.createObjectURL(blob), a=document.createElement("a"); a.href=url;a.download=`lista-${getCode()||"compras"}.txt`; a.click(); URL.revokeObjectURL(url);}
function restore(){if(!confirm("Deseja restaurar a lista padrão e apagar alterações locais?"))return; produtos=[...produtosPadrao].map(p=>({...p,estoqueAtual:0})); totalCompra=0; checks={}; save(K.L,[]); store(); renderAll(); sync();}
function screen(name){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active")); document.getElementById(`screen-${name}`).classList.add("active"); document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.go===name));}
function renderCategories(){renderChips("chipsCategorias",catProd,cat=>{catProd=cat; store(); renderCategories(); renderProducts(document.getElementById("buscaProduto").value)}); renderChips("chipsMercado",catMerc,cat=>{catMerc=cat; store(); renderCategories(); renderMarket();});}
function renderAll(){document.getElementById("total").textContent=m(totalCompra); document.getElementById("toggleOcultarComprados").checked=ocultar; document.getElementById("deviceName").value=getDev(); codeUI(); renderCategories(); renderProducts(document.getElementById("buscaProduto").value||""); renderMarket(); dashboard(); renderLogs();}
function openApp(){document.getElementById("entryScreen").classList.add("hidden"); document.getElementById("appShell").classList.remove("hidden"); codeUI();}
function showEntry(){document.getElementById("entryScreen").classList.remove("hidden"); document.getElementById("appShell").classList.add("hidden"); document.getElementById("accessCode").value=getCode(); document.getElementById("deviceNameEntry").value=getDev();}
async function enterApp(){const code=(document.getElementById("accessCode").value||"").trim().toLowerCase(), nome=(document.getElementById("deviceNameEntry").value||"").trim(); if(!code){alert("Digite o código da lista.");return;} setCode(code); if(nome)setDev(nome); store(); openApp(); renderAll(); await startFirebase();}
function swapCode(){if(!confirm("Deseja trocar o código da lista agora?"))return; showEntry();}
function bind(){document.querySelectorAll("[data-go]").forEach(btn=>btn.onclick=()=>screen(btn.dataset.go)); document.getElementById("btnStartShopping").onclick=()=>screen("market"); document.getElementById("btnAdicionarProduto").onclick=addProduct; document.getElementById("btnAtualizarMercado").onclick=renderMarket; document.getElementById("btnSalvar").onclick=async()=>{store(); await sync(); alert("Dados salvos.");}; document.getElementById("btnRestaurar").onclick=restore; document.getElementById("btnAdicionarValor").onclick=addValue; document.getElementById("btnZerarTotal").onclick=resetValue; document.getElementById("btnExportar").onclick=exportList; document.getElementById("btnEntrar").onclick=enterApp; document.getElementById("btnTrocarCodigo").onclick=swapCode; document.getElementById("btnTrocarCodigo2").onclick=swapCode; document.getElementById("accessCode").onkeydown=e=>{if(e.key==="Enter")enterApp()}; document.getElementById("deviceNameEntry").onkeydown=e=>{if(e.key==="Enter")enterApp()}; document.getElementById("valorItem").onkeydown=e=>{if(e.key==="Enter")addValue()}; document.getElementById("buscaProduto").oninput=e=>renderProducts(e.target.value); document.getElementById("buscaMercado").oninput=renderMarket; document.getElementById("toggleOcultarComprados").onchange=e=>{ocultar=e.target.checked; store(); renderMarket();}; document.getElementById("deviceName").oninput=e=>setDev(e.target.value); document.getElementById("novoUnidade").value="un";}
function pwa(){if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));} window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;document.getElementById("btnInstall").classList.remove("hidden");}); document.getElementById("btnInstall").onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;document.getElementById("btnInstall").classList.add("hidden");};}
window.app={updateProduct,removeProduct,setBought,toggleBought:(id)=>setBought(id,!checks[id])};
(async function(){loadState(); normalize(); bind(); pwa(); renderAll(); if(getCode()){openApp(); await startFirebase();} else {showEntry(); status("Sem código");}})();
